import atexit
import os
import shutil
import soundfile as sf
from mlx_audio.tts.utils import load_model
import mlx.core as mx

SAMPLE_RATE_HZ = 24000
DEFAULT_TTS_MODEL = "mlx-community/Qwen3-TTS-12Hz-1.7B-Base-bf16"

project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "../.."))
script_directory = os.path.dirname(__file__)
python_cache_directory = os.path.join(script_directory, "__pycache__")


def _remove_python_cache_directory():
    if os.path.isdir(python_cache_directory):
        # WHAT: these scripts are developer tooling, so any generated bytecode cache
        # should be treated as disposable local noise and removed after each run.
        shutil.rmtree(python_cache_directory, ignore_errors=True)


def install_python_cache_cleanup():
    atexit.register(_remove_python_cache_directory)


def load_env_from_project_root():
    # Load .env from project root (simple parser, no external dependency)
    env_path = os.path.join(project_root, ".env")
    if os.path.exists(env_path):
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, _, value = line.partition("=")
                    os.environ.setdefault(key.strip(), value.strip())


def require_voice_reference(path):
    if not os.path.exists(path):
        raise SystemExit(f"Missing voice reference sample: {path}")


def load_tts_model(model_name):
    print(f"Loading {model_name}...")
    return load_model(model_name)


def save_generated_audio(path, audio_array, sample_rate):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    if isinstance(audio_array, mx.array):
        audio_array = audio_array.tolist()
    sf.write(path, audio_array, sample_rate)
