import atexit
import os
import shutil
import soundfile as sf
from mlx_audio.tts.utils import load_model
import mlx.core as mx

project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "../.."))
script_directory = os.path.dirname(__file__)
python_cache_directory = os.path.join(script_directory, "__pycache__")


def remove_python_cache_directory():
    if os.path.isdir(python_cache_directory):
        # WHAT: this script is developer tooling, so any generated bytecode cache
        # should be treated as disposable local noise and removed after each run.
        shutil.rmtree(python_cache_directory, ignore_errors=True)


atexit.register(remove_python_cache_directory)

# Load .env from project root
env_path = os.path.join(project_root, ".env")
if os.path.exists(env_path):
    with open(env_path) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, _, value = line.partition("=")
                os.environ.setdefault(key.strip(), value.strip())

reference_audio = os.path.join(project_root, "dev/audio/data/sample.wav")
output_directory = os.path.join(project_root, "dev/audio/data")
output_file = os.path.join(output_directory, "clone-test.wav")
os.makedirs(output_directory, exist_ok=True)

if not os.path.exists(reference_audio):
    raise SystemExit(f"Missing voice reference sample: {reference_audio}")

if os.path.exists(output_file):
    print(f"Skipping clone test (exists): {output_file}")
    raise SystemExit(0)

model_name = os.environ.get("AUDIO_BASE_MODEL", "mlx-community/Qwen3-TTS-12Hz-1.7B-Base-bf16")
print(f"Loading {model_name}...")
model = load_model(model_name)

print("Generating with voice clone...")
results = list(model.generate(
    text="Ironveil station. Large shipyard. Ore Dominion.",
    ref_audio=reference_audio,
    ref_text="Mossgate. Small habitat. Bio-annex. Riftwake. Jumpship. Skyshift Cooperative.",
))

audio = results[0].audio
if isinstance(audio, mx.array):
    audio = audio.tolist()

sf.write(output_file, audio, 24000)
print(f"Saved to {output_file}")
